### ISSUE TITLE
Inlined web workers?

### ISSUE THREAD

**Issue by Burtan** [avwie/scribbles#1]
Hey, did you try inlining web workers to avoid having a web worker module?
https://medium.com/@dee_bloo/make-multithreading-easier-with-inline-web-workers-a58723428a42

**Comment by avwie** [comment]
Hi,

Hmm, interesting. I’ll check it out!
Thanks for letting me know.

**Comment by Burtan** [comment]
https://discuss.kotlinlang.org/t/implementing-a-webworker-in-kotlin/3892/11

I got a running minimal example!
One thing to keep in mind is not to use any scoped variables. Any data for the web workers has to be send via postMessage equally as in regular web workers.

**Comment by avwie** [comment]
Awesome, I was just experimenting with it but ran into a lot of problems. I'll look at your code!

**Comment by avwie** [comment]
Please keep in mind that you can not access anything Kotlin related. The Kotlin/JS stdlib is not loaded inside the web-worker.

**Comment by avwie** [comment]
Closed
